version: '2'
services:

  server:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000

  cron:
    build:
      context: .
      dockerfile: Dockerfile-cron
    depends_on:
      - server
    environment:
      CRON: 1

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    depends_on:
      - server
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
